name: cognify_flutter
description: Cognify Flutter App

version: 1.0.2+3

environment:
  sdk: '^3.8.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # Background Service (currently disabled to prevent permission crashes)
  flutter_background_service: ^5.1.0
  wakelock_plus: ^1.2.1           # Keep device awake
  connectivity_plus: ^5.0.2       # Network connectivity monitoring

  # HTTP & API
  http: ^1.4.0
  dio: ^5.4.0                     # Advanced HTTP client
  web_socket_channel: ^2.4.0      # WebSocket support

  # Storage & Database
  shared_preferences: ^2.2.2      # Local storage
  flutter_secure_storage: ^9.0.0  # Secure storage
  hive: ^2.2.3                    # Local NoSQL database
  hive_flutter: ^1.1.0            # Hive Flutter bindings
  sqflite: ^2.3.0                 # SQLite database

  # Document Processing
  pdf: ^3.10.4                    # PDF parsing and creation
  html: ^0.15.4                   # HTML parsing
  archive: ^3.4.10                # ZIP/archive handling
  mime: ^1.0.4                    # MIME type detection
  xml: ^6.4.2                     # XML parsing

  # Vector Operations & Math
  vector_math: ^2.1.4             # Vector mathematics

  # Text Processing & NLP
  string_similarity: ^2.0.0       # Text similarity calculations
  crypto: ^3.0.3                  # Cryptographic functions
  convert: ^3.1.1                 # Encoding/decoding utilities

  # State Management
  provider: ^6.1.1                # State management

  # Navigation
  go_router: ^13.2.0              # Routing

  # UI Components
  flutter_markdown: ^0.6.18       # Markdown rendering
  cached_network_image: ^3.3.1    # Image caching
  flutter_animate: ^4.5.0         # Advanced animations

  # File Handling
  file_picker: ^8.0.0+1           # File selection
  image_picker: ^1.0.4            # Image picker

  # Utilities
  url_launcher: ^6.2.1            # Launch URLs
  webview_flutter: ^4.13.0         # WebView
  path_provider: ^2.1.4           # File paths
  path: ^1.8.3                    # Path manipulation
  uuid: ^4.2.1                    # UUID generation
  intl: ^0.19.0                   # Internationalization

  # Background Processing
  isolate: ^2.1.1                 # Background task management (optional - can be enabled later)
  # workmanager: ^0.5.2             # Background task management

  # Logging & Debugging
  logger: ^2.0.2+1                # Advanced logging

  # JSON & Serialization
  json_annotation: ^4.8.1         # JSON serialization annotations

  # Development
  cupertino_icons: ^1.0.2

  # Device Features
  haptic_feedback: ^0.5.1+1               # Vibration support
  flutter_svg: ^2.2.0
  webview_flutter_android: ^4.8.2
  jovial_svg: ^1.1.27
  permission_handler: ^11.3.1                  # Storage permissions
  app_links: ^6.4.0

  purchases_flutter: ^8.8.0

  # Firebase (conservative stable pins for Dart 3.8)
  firebase_core: ^2.27.2
  firebase_auth: ^4.17.8
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.7            # Code generation
  json_serializable: ^6.7.1       # JSON serialization code generation
  hive_generator: ^2.0.1          # Hive type adapters generation

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/roadmaps/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
