// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQZw5pKiJ4XTK0sQxNcYW1Fe0hZI2yIwM',
    appId: '1:702035468371:web:your-web-app-id',
    messagingSenderId: '702035468371',
    projectId: 'cognify-eb0a2',
    authDomain: 'cognify-eb0a2.firebaseapp.com',
    storageBucket: 'cognify-eb0a2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZw5pKiJ4XTK0sQxNcYW1Fe0hZI2yIwM',
    appId: '1:702035468371:android:1b52df4446f2404791e6a6',
    messagingSenderId: '702035468371',
    projectId: 'cognify-eb0a2',
    storageBucket: 'cognify-eb0a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHYQ7W3jhJDRtDzk7Fr-0xZrB-zYJ8tE',
    appId: '1:702035468371:ios:5990b7f329907f2f91e6a6',
    messagingSenderId: '702035468371',
    projectId: 'cognify-eb0a2',
    storageBucket: 'cognify-eb0a2.firebasestorage.app',
    iosBundleId: 'com.umerfarooq1995.cognifyFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwHYQ7W3jhJDRtDzk7Fr-0xZrB-zYJ8tE',
    appId: '1:702035468371:ios:5990b7f329907f2f91e6a6',
    messagingSenderId: '702035468371',
    projectId: 'cognify-eb0a2',
    storageBucket: 'cognify-eb0a2.firebasestorage.app',
    iosBundleId: 'com.umerfarooq1995.cognifyFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQZw5pKiJ4XTK0sQxNcYW1Fe0hZI2yIwM',
    appId: '1:702035468371:web:your-web-app-id',
    messagingSenderId: '702035468371',
    projectId: 'cognify-eb0a2',
    authDomain: 'cognify-eb0a2.firebaseapp.com',
    storageBucket: 'cognify-eb0a2.firebasestorage.app',
  );
}